# Generated by Django 5.2.16 on 2026-08-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='código institucional')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('kind', models.CharField(choices=[('educational_center', 'Centro educativo'), ('departmental_office', 'Dirección Departamental'), ('ministry_unit', 'Unidad del Ministerio'), ('other', 'Otra institución')], max_length=30, verbose_name='tipo')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='departamento')),
                ('municipality', models.CharField(blank=True, max_length=100, verbose_name='municipio')),
                ('address', models.TextField(blank=True, verbose_name='dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
            ],
            options={
                'verbose_name': 'institución',
                'verbose_name_plural': 'instituciones',
                'ordering': ('name',),
            },
        ),
    ]
