# Generated by Django 5.2.16 on 2026-08-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('technical_admin', 'Administrador técnico'), ('audit_manager', 'Directora de Auditoría'), ('auditor', 'Auditor'), ('institution', 'Responsable institucional')], default='institution', max_length=24, verbose_name='rol'),
        ),
    ]
