# Generated by Django 5.2.16 on 2026-08-03 21:49

import apps.audits.models
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=60, unique=True, verbose_name='referencia')),
                ('title', models.CharField(max_length=300, verbose_name='título')),
                ('report_file', models.FileField(blank=True, upload_to=apps.audits.models.private_upload_path, validators=[apps.core.validators.validate_evidence_file], verbose_name='informe PDF')),
                ('report_date', models.DateField(blank=True, null=True, verbose_name='fecha del informe')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='inicio del período')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='fin del período')),
                ('response_deadline', models.DateField(blank=True, null=True, verbose_name='fecha límite general')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Enviado'), ('in_response', 'En respuesta'), ('under_review', 'En revisión'), ('correction_required', 'Requiere corrección'), ('closed', 'Cerrado')], default='draft', max_length=30, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('assigned_auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='auditor responsable')),
                ('audited_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_cases', to='institutions.organization', verbose_name='institución auditada')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cases', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'expediente de auditoría',
                'verbose_name_plural': 'expedientes de auditoría',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80, verbose_name='acción')),
                ('target_type', models.CharField(blank=True, max_length=80, verbose_name='tipo de objeto')),
                ('target_id', models.CharField(blank=True, max_length=80, verbose_name='identificador')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_logs', to='audits.auditcase', verbose_name='expediente')),
            ],
            options={
                'verbose_name': 'evento de bitácora',
                'verbose_name_plural': 'bitácora',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='número')),
                ('title', models.CharField(max_length=350, verbose_name='título')),
                ('risk_level', models.CharField(choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=10, verbose_name='riesgo')),
                ('condition', models.TextField(blank=True, verbose_name='condición')),
                ('criteria', models.TextField(blank=True, verbose_name='criterio')),
                ('cause', models.TextField(blank=True, verbose_name='causa')),
                ('effect', models.TextField(blank=True, verbose_name='efecto')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audits.auditcase', verbose_name='expediente')),
            ],
            options={
                'verbose_name': 'hallazgo',
                'verbose_name_plural': 'hallazgos',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='número')),
                ('text', models.TextField(verbose_name='recomendación')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='fecha límite')),
                ('evidence_requirements', models.TextField(blank=True, verbose_name='evidencias requeridas')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('submitted', 'Respuesta enviada'), ('under_review', 'En revisión'), ('correction_required', 'Requiere corrección'), ('complied', 'Cumplida'), ('partial', 'Parcialmente cumplida'), ('not_complied', 'No cumplida')], default='pending', max_length=30, verbose_name='estado')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='audits.finding', verbose_name='hallazgo')),
                ('responsible_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='institutions.organization', verbose_name='institución responsable')),
            ],
            options={
                'verbose_name': 'recomendación',
                'verbose_name_plural': 'recomendaciones',
                'ordering': ('finding__number', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='versión')),
                ('declared_status', models.CharField(choices=[('not_started', 'No iniciada'), ('in_progress', 'En proceso'), ('completed', 'Completada'), ('unable', 'No fue posible cumplir')], max_length=20, verbose_name='estado declarado')),
                ('action_description', models.TextField(verbose_name='acciones realizadas')),
                ('action_date', models.DateField(blank=True, null=True, verbose_name='fecha de ejecución')),
                ('responsible_name', models.CharField(max_length=200, verbose_name='nombre del responsable')),
                ('responsible_job_title', models.CharField(max_length=150, verbose_name='cargo del responsable')),
                ('non_compliance_reason', models.TextField(blank=True, verbose_name='motivo de incumplimiento')),
                ('action_plan', models.TextField(blank=True, verbose_name='plan de acción pendiente')),
                ('expected_completion_date', models.DateField(blank=True, null=True, verbose_name='fecha estimada de cumplimiento')),
                ('accuracy_declaration', models.BooleanField(default=False, verbose_name='declaración de veracidad')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='enviada')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='audits.recommendation', verbose_name='recomendación')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_responses', to=settings.AUTH_USER_MODEL, verbose_name='enviada por')),
            ],
            options={
                'verbose_name': 'respuesta',
                'verbose_name_plural': 'respuestas',
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.audits.models.private_upload_path, validators=[apps.core.validators.validate_evidence_file], verbose_name='archivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='nombre original')),
                ('category', models.CharField(choices=[('minutes', 'Acta'), ('accounting', 'Registro contable'), ('banking', 'Documento bancario'), ('invoice', 'Factura o recibo'), ('contract', 'Contrato'), ('image', 'Imagen'), ('other', 'Otra evidencia')], default='other', max_length=20, verbose_name='categoría')),
                ('description', models.CharField(max_length=300, verbose_name='descripción')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='tamaño')),
                ('sha256', models.CharField(max_length=64, verbose_name='huella SHA-256')),
                ('scan_status', models.CharField(choices=[('pending', 'Pendiente de análisis'), ('clean', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10, verbose_name='estado de análisis')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='subida')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL, verbose_name='subida por')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='audits.response', verbose_name='respuesta')),
            ],
            options={
                'verbose_name': 'evidencia',
                'verbose_name_plural': 'evidencias',
                'ordering': ('uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('correction_required', 'Requiere corrección'), ('complied', 'Cumplida'), ('partial', 'Parcialmente cumplida'), ('not_complied', 'No cumplida')], max_length=30, verbose_name='resultado')),
                ('comments', models.TextField(verbose_name='comentarios de Auditoría')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='revisada')),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='audits.response', verbose_name='respuesta')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='revisada por')),
            ],
            options={
                'verbose_name': 'revisión',
                'verbose_name_plural': 'revisiones',
                'ordering': ('-reviewed_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.UniqueConstraint(fields=('case', 'number'), name='unique_finding_number_per_case'),
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('finding', 'number'), name='unique_recommendation_number_per_finding'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('recommendation', 'version'), name='unique_response_version_per_recommendation'),
        ),
    ]
