# Generated by Django 5.2.16 on 2026-08-12 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditcase',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending_publication', 'Pendiente de aprobación'), ('published', 'Enviado'), ('in_response', 'En respuesta'), ('under_review', 'En revisión'), ('correction_required', 'Requiere corrección'), ('pending_closure', 'Cierre solicitado'), ('closed', 'Cerrado')], default='draft', max_length=30, verbose_name='estado'),
        ),
        migrations.CreateModel(
            name='CaseDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('publication', 'Publicación'), ('closure', 'Cierre')], max_length=20, verbose_name='tipo de decisión')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('returned', 'Devuelta')], default='pending', max_length=20, verbose_name='estado')),
                ('request_note', models.TextField(blank=True, verbose_name='nota de solicitud')),
                ('previous_case_status', models.CharField(blank=True, max_length=30, verbose_name='estado anterior')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='solicitada')),
                ('decision_note', models.TextField(blank=True, verbose_name='justificación de la decisión')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decidida')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='audits.auditcase', verbose_name='expediente')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_case_decisions', to=settings.AUTH_USER_MODEL, verbose_name='decidida por')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_case_decisions', to=settings.AUTH_USER_MODEL, verbose_name='solicitada por')),
            ],
            options={
                'verbose_name': 'decisión directiva',
                'verbose_name_plural': 'decisiones directivas',
                'ordering': ('-requested_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('case',), name='one_pending_decision_per_case')],
            },
        ),
    ]
