# Generated by Django 5.2.16 on 2026-08-14 14:44

import apps.audits.models
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_reports(apps, schema_editor):
    AuditCase = apps.get_model('audits', 'AuditCase')
    AuditDocument = apps.get_model('audits', 'AuditDocument')
    private_statuses = {'draft', 'pending_publication'}
    for case in AuditCase.objects.exclude(report_file=''):
        if case.status == 'draft':
            document_status = 'draft'
        elif case.status == 'pending_publication':
            document_status = 'pending_approval'
        else:
            document_status = 'approved'
        AuditDocument.objects.create(
            case_id=case.pk,
            organization_id=case.audited_organization_id,
            document_type='report',
            reference=case.reference,
            title=case.title,
            document_date=case.report_date,
            version=1,
            status=document_status,
            visibility='audit_only' if case.status in private_statuses else 'institution',
            file=case.report_file.name,
            original_filename=f'{case.reference}.pdf',
            size=0,
            sha256='',
            uploaded_by_id=case.created_by_id,
        )


def remove_migrated_legacy_reports(apps, schema_editor):
    AuditDocument = apps.get_model('audits', 'AuditDocument')
    AuditDocument.objects.filter(
        document_type='report',
        version=1,
        sha256='',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_alter_auditcase_status_casedecision'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDayHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='fecha')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'asueto',
                'verbose_name_plural': 'asuetos',
                'ordering': ('date',),
            },
        ),
        migrations.AddField(
            model_name='recommendation',
            name='carried_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carried_forward_recommendations', to='audits.recommendation', verbose_name='recomendación anterior'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='no_response_recorded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='incumplimiento automático registrado'),
        ),
        migrations.CreateModel(
            name='AuditDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('historical_report', 'Informe histórico'), ('report', 'Informe del expediente'), ('notification', 'Notificación'), ('other', 'Otro documento')], max_length=30, verbose_name='tipo de documento')),
                ('reference', models.CharField(blank=True, max_length=80, verbose_name='referencia')),
                ('title', models.CharField(max_length=300, verbose_name='título')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='fecha del documento')),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='versión')),
                ('status', models.CharField(choices=[('historical', 'Histórico'), ('draft', 'Borrador'), ('pending_approval', 'Pendiente de aprobación'), ('approved', 'Aprobado'), ('returned', 'Devuelto')], max_length=24, verbose_name='estado')),
                ('visibility', models.CharField(choices=[('audit_only', 'Solo Auditoría'), ('institution', 'Visible para la institución')], default='audit_only', max_length=20, verbose_name='visibilidad')),
                ('file', models.FileField(upload_to=apps.audits.models.audit_document_upload_path, validators=[apps.core.validators.validate_evidence_file], verbose_name='archivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='nombre original')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='tamaño')),
                ('sha256', models.CharField(max_length=64, verbose_name='huella SHA-256')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='cargado')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='audits.auditcase', verbose_name='expediente')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_documents', to='institutions.organization', verbose_name='institución')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_audit_documents', to=settings.AUTH_USER_MODEL, verbose_name='cargado por')),
            ],
            options={
                'verbose_name': 'documento de auditoría',
                'verbose_name_plural': 'documentos de auditoría',
                'ordering': ('-document_date', '-uploaded_at'),
            },
        ),
        migrations.RunPython(
            migrate_legacy_reports,
            remove_migrated_legacy_reports,
        ),
        migrations.AddField(
            model_name='casedecision',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='audits.auditdocument', verbose_name='documento sometido'),
        ),
        migrations.CreateModel(
            name='DeadlineExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_deadline', models.DateField(verbose_name='fecha límite anterior')),
                ('business_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='días hábiles concedidos')),
                ('new_deadline', models.DateField(verbose_name='nueva fecha límite')),
                ('reason', models.TextField(verbose_name='motivo')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='registrada')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granted_deadline_extensions', to=settings.AUTH_USER_MODEL, verbose_name='registrada por')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deadline_extensions', to='audits.recommendation', verbose_name='recomendación')),
            ],
            options={
                'verbose_name': 'prórroga',
                'verbose_name_plural': 'prórrogas',
                'ordering': ('granted_at',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=60, verbose_name='número o literal')),
                ('text', models.TextField(verbose_name='recomendación')),
                ('responsible_description', models.CharField(blank=True, max_length=300, verbose_name='responsable indicado en el informe')),
                ('status', models.CharField(choices=[('partial', 'Parcialmente cumplida'), ('not_complied', 'No cumplida')], max_length=20, verbose_name='estado anterior')),
                ('comments', models.TextField(blank=True, verbose_name='comentario anterior')),
                ('original_deadline', models.DateField(blank=True, null=True, verbose_name='fecha límite original')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='registrada')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_historical_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='registrada por')),
                ('responsible_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_recommendations', to='institutions.organization', verbose_name='institución responsable')),
                ('source_document', models.ForeignKey(limit_choices_to={'document_type': 'historical_report'}, on_delete=django.db.models.deletion.PROTECT, related_name='historical_recommendations', to='audits.auditdocument', verbose_name='informe de origen')),
            ],
            options={
                'verbose_name': 'recomendación histórica',
                'verbose_name_plural': 'recomendaciones históricas',
                'ordering': ('source_document__document_date', 'number'),
            },
        ),
        migrations.AddField(
            model_name='recommendation',
            name='source_recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_recommendations', to='audits.historicalrecommendation', verbose_name='recomendación histórica de origen'),
        ),
        migrations.AddConstraint(
            model_name='auditdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('case__isnull', False)), fields=('case', 'document_type', 'version'), name='unique_document_version_per_case_and_type'),
        ),
        migrations.AddConstraint(
            model_name='historicalrecommendation',
            constraint=models.UniqueConstraint(fields=('source_document', 'number'), name='unique_historical_recommendation_number_per_document'),
        ),
    ]
